//! Direct next-byte training, mirroring the architecture path in
//! upstream `train_enwik8.py` without network access or a 100 MB dataset.
//!
//! This tiny corpus only demonstrates the forward/loss/backward/optimizer and
//! recurrent-sampling mechanics; it cannot produce meaningful prose.
//!
//! ```console
//! cargo run --offline --example train_tiny_bytes -- 10
//! ```

use bdh_cq_llm::{Bdh, BdhConfig, BdhError, BdhForwardOptions, ModelInput};
use burn::{
    backend::{Autodiff, NdArray},
    grad_clipping::GradientClippingConfig,
    module::AutodiffModule,
    nn::loss::CrossEntropyLossConfig,
    optim::{AdamWConfig, GradientsParams, Optimizer},
    tensor::{Int, Tensor, TensorData, backend::Backend},
};

type Inner = NdArray<f32>;
type Train = Autodiff<Inner>;

const SEQUENCE: usize = 48;

fn main() -> Result<(), Box<dyn std::error::Error>> {
    let steps = std::env::args()
        .nth(1)
        .map(|value| value.parse::<usize>())
        .transpose()?
        .unwrap_or(5);
    let device = Default::default();
    Train::seed(&device, 42);

    // Upstream enwik8 defaults are D=384, depth=6, H*Q=2048. These study
    // dimensions make a full optimization step quick on the ndarray backend.
    let mut model = BdhConfig::new(256, 24)
        .with_depth(2)
        .with_heads(2)
        .with_dim_qk_heads(96)
        .init::<Train>(&device)?;
    let mut optimizer = AdamWConfig::new()
        .with_beta_2(0.95)
        .with_weight_decay(0.1)
        .with_grad_clipping(Some(GradientClippingConfig::Norm(1.0)))
        .init();
    let criterion = CrossEntropyLossConfig::new().init(&device);

    let sentence =
        b"the recurrent state remembers earlier bytes; the shared block reasons in depth. ";
    let corpus: Vec<u8> = sentence.iter().copied().cycle().take(4096).collect();

    for step in 0..steps {
        let start = (step * SEQUENCE) % (corpus.len() - SEQUENCE - 1);
        let window = &corpus[start..start + SEQUENCE + 1];
        let input = byte_ids::<Train>(&window[..SEQUENCE], &device);
        let targets = byte_ids::<Train>(&window[1..], &device).reshape([SEQUENCE]);

        // Training samples are independent, as in the shuffled enwik8 window
        // loader, so no Memory is carried from one optimizer update to another.
        let logits = model
            .forward(ModelInput::TokenIds(input), None, Default::default())?
            .logits
            .expect("default forward requests logits")
            .reshape([SEQUENCE, 256]);
        let loss = criterion.forward(logits, targets);
        let scalar = loss.to_data().to_vec::<f32>()?[0];
        let gradients = GradientsParams::from_grads(loss.backward(), &model);

        // Linear warmup followed by the same cosine-shaped decay idea used by
        // the upstream script (compressed to this example's tiny step count).
        let warmup = ((step + 1) as f64 / 5.0).min(1.0);
        let progress = step as f64 / steps.max(1) as f64;
        let learning_rate = 3e-3 * warmup * 0.5 * (1.0 + (std::f64::consts::PI * progress).cos());
        model = optimizer.step(learning_rate, model, gradients);
        println!("step {step:03}: loss={scalar:.5}, lr={learning_rate:.6}");
    }

    // Convert parameters to the non-autodiff inner backend for inference, the
    // Burn equivalent of PyTorch's no-grad sampling context.
    let inference_model = model.valid();
    let generated = greedy_sample(&inference_model, b"the recurrent ", 24)?;
    let escaped: String = generated
        .into_iter()
        .flat_map(std::ascii::escape_default)
        .map(char::from)
        .collect();
    println!("generated bytes: {escaped}");
    Ok(())
}

/// Ingest a prompt once, then carry its fixed-size memory one byte at a time.
fn greedy_sample<B: Backend>(
    model: &Bdh<B>,
    prompt: &[u8],
    length: usize,
) -> Result<Vec<u8>, BdhError> {
    let device = model.device();
    let prompt_output = model.forward(
        ModelInput::TokenIds(byte_ids::<B>(prompt, &device)),
        None,
        Default::default(),
    )?;
    let mut memory = prompt_output.memory;
    let mut logits = prompt_output
        .logits
        .expect("default forward requests logits");
    let mut generated = Vec::with_capacity(length);

    for _ in 0..length {
        let [_, sequence, vocabulary] = logits.dims();
        let values = logits
            .slice([0..1, sequence - 1..sequence, 0..vocabulary])
            .reshape([vocabulary])
            .into_data()
            .to_vec::<f32>()
            .expect("model logits are float32 on this backend");
        let token = values
            .iter()
            .enumerate()
            .max_by(|(_, left), (_, right)| left.total_cmp(right))
            .map(|(index, _)| index)
            .expect("the byte vocabulary is non-empty");
        generated.push(token as u8);

        let output = model.forward(
            ModelInput::TokenIds(byte_ids::<B>(&[token as u8], &device)),
            Some(memory),
            BdhForwardOptions::default(),
        )?;
        logits = output.logits.expect("default forward requests logits");
        memory = output.memory;
    }
    Ok(generated)
}

fn byte_ids<B: Backend>(bytes: &[u8], device: &B::Device) -> Tensor<B, 2, Int> {
    let ids: Vec<i64> = bytes.iter().map(|byte| i64::from(*byte)).collect();
    Tensor::from_data(TensorData::new(ids, [1, bytes.len()]), device)
}
